import { ArrowUpRight, Search, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { PageIntro, SiteFooter, SiteHeader } from "@/components/SiteShell";
import { trpc } from "@/lib/trpc";

const categories = ["tous", "accueil", "service", "animation", "technique", "art", "logistique"] as const;
type Category = Exclude<(typeof categories)[number], "tous">;

export default function Directory() {
  const [location] = useLocation(); const initialCategory = new URLSearchParams(location.split("?")[1] ?? "").get("categorie") as Category | null; const [category, setCategory] = useState<Category | undefined>(initialCategory && categories.includes(initialCategory) ? initialCategory : undefined); const [search, setSearch] = useState("");
  const input = useMemo(() => ({ category, search: search.trim() || undefined }), [category, search]); const { data: talents = [], isLoading } = trpc.talents.publicList.useQuery(input);
  return <div className="min-h-screen bg-paper"><SiteHeader /><PageIntro eyebrow="L’annuaire" title="Chercher un geste, une présence, un savoir-faire.">Les profils visibles ici ont donné un consentement explicite à leur publication et ont été validés par la coordination. L’annuaire ne présente aucune situation personnelle.</PageIntro><main className="container py-10 md:py-16"><div className="flex flex-col gap-5 border-b border-ink/10 pb-8"><label className="relative max-w-xl"><Search className="absolute left-4 top-3.5 h-5 w-5 text-ink/45" /><input className="field-control rounded-full py-3 pl-12" value={search} onChange={event => setSearch(event.target.value)} placeholder="Une compétence, une ville, un métier…" /></label><div className="flex flex-wrap gap-2">{categories.map(item => <button key={item} onClick={() => setCategory(item === "tous" ? undefined : item)} className={`rounded-full border px-4 py-2 text-sm font-medium capitalize transition ${category === item || (item === "tous" && !category) ? "border-ink bg-ink text-paper" : "border-ink/15 bg-white text-ink hover:border-ink"}`}>{item}</button>)}</div></div>
  {isLoading ? <div className="py-20 text-center text-ink/55">Recherche des profils disponibles…</div> : talents.length ? <div className="grid gap-4 py-10 sm:grid-cols-2 lg:grid-cols-3">{talents.map(talent => <article key={talent.id} className="group flex min-h-64 flex-col justify-between rounded-[1.5rem] border border-ink/10 bg-white p-6 shadow-card transition hover:-translate-y-1"><div><div className="flex items-start justify-between gap-3"><span className="status-pill bg-lime">{talent.category}</span><Sparkles className="h-5 w-5 text-coral" /></div><h2 className="mt-7 font-editorial text-3xl">{talent.professionalName}</h2><p className="mt-2 text-sm font-semibold text-ink/65">{talent.headline}</p><p className="mt-5 line-clamp-2 text-sm leading-6 text-ink/60">{talent.skills}</p></div><div className="mt-5 flex items-center justify-between border-t border-ink/10 pt-4 text-xs text-ink/55"><span>{talent.city} · {talent.region}</span><span className="inline-flex items-center gap-1 font-semibold text-ink">Profil vérifié <ArrowUpRight size={14} /></span></div></article>)}</div> : <div className="my-10 grid gap-8 rounded-[1.8rem] bg-sand p-8 md:grid-cols-[1fr_.8fr] md:p-12"><div><p className="eyebrow">Annuaire en construction</p><h2 className="mt-4 font-editorial text-4xl">Les profils apparaissent après validation humaine.</h2><p className="mt-5 max-w-xl leading-7 text-ink/65">Aucun profil ne correspond encore à ces critères. Les premiers talents sont en cours de vérification afin que chaque mise en relation repose sur un consentement réel et un cadre de mission clair.</p></div><div className="flex items-center"><Link href="/talents" className="button-ink w-full gap-2 md:w-auto">Déposer mon profil <ArrowUpRight size={17} /></Link></div></div>}</main><SiteFooter /></div>;
}
