import { BadgeCheck, CheckCircle2, Handshake, HeartHandshake, ShieldQuestion } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { PageIntro, SiteFooter, SiteHeader } from "@/components/SiteShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

export default function PartnerPage() { return <div className="min-h-screen bg-paper"><SiteHeader /><PageIntro eyebrow="Association & partenaires" title="Associer des forces, sans confondre les rôles.">Lumière Commune souhaite travailler avec des structures qui protègent les personnes et valorisent leurs compétences. Toute coopération est examinée avant d’être présentée publiquement.</PageIntro><main className="container py-12 md:py-18"><section className="grid gap-5 md:grid-cols-3"><Card icon={<HeartHandshake />} title="Le rôle de l’association">Favoriser des opportunités de participation et de travail choisies, accompagner les personnes qui le souhaitent et faire grandir un réseau local de confiance.</Card><Card icon={<BadgeCheck />} title="Les critères d’adhésion">Un cadre d’accompagnement clair, la non-discrimination, le respect du consentement, et une transparence sur les conditions de mission.</Card><Card icon={<ShieldQuestion />} title="Le statut public">Une candidature commence toujours « en cours d’échange ». Seule une validation humaine documentée permet d’afficher « partenaire validé ».</Card></section><section className="mt-14 grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Devenir partenaire</p><h2 className="mt-5 font-editorial text-5xl leading-[.95]">Construisons un cadre qui protège avant de promettre.</h2><p className="mt-7 leading-7 text-ink/65">Une candidature ne vaut pas partenariat. Après réception, la coordination échange avec la structure sur les modalités d’accompagnement, de confidentialité et de juste rémunération avant toute mention publique.</p><div className="mt-8 rounded-[1.5rem] bg-lime p-6"><Handshake className="text-coral" /><p className="mt-4 text-sm leading-6">Aucun parrainage nominatif n’est annoncé à ce stade. Toute personnalité ou organisation citée devra avoir donné un accord écrit préalable.</p></div></div><PartnerForm /></section></main><SiteFooter /></div>; }
function Card({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <article className="rounded-[1.5rem] border border-ink/10 bg-white p-6 shadow-card"><div className="text-coral">{icon}</div><h2 className="mt-7 font-editorial text-3xl">{title}</h2><p className="mt-3 text-sm leading-6 text-ink/65">{children}</p></article>; }
function PartnerForm() { const [sent, setSent] = useState(false); const submit = trpc.partners.submit.useMutation({ onSuccess: () => { setSent(true); toast.success("Candidature reçue."); }, onError: error => toast.error(error.message) }); if (sent) return <div className="form-card"><CheckCircle2 className="h-9 w-9 text-coral" /><h2 className="mt-5 font-editorial text-4xl">Votre candidature est en cours d’échange.</h2><p className="mt-4 leading-7 text-ink/65">Elle ne sera jamais publiée comme un partenariat avant validation humaine.</p></div>; const form = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); submit.mutate({ organisationName: String(data.get("organisationName")), contactName: String(data.get("contactName")), contactEmail: String(data.get("contactEmail")), website: String(data.get("website") || ""), supportFramework: String(data.get("supportFramework")) }); }; return <form onSubmit={form} className="form-card"><p className="eyebrow">Candidature structure</p><div className="mt-6 grid gap-5"><Field name="organisationName" label="Nom de la structure" required /><Field name="contactName" label="Personne de contact" required /><Field name="contactEmail" label="E-mail professionnel" type="email" required /><Field name="website" label="Site web (facultatif)" type="url" /><label><span className="field-label">Votre cadre d’accompagnement</span><textarea required name="supportFramework" className="field-control min-h-36" placeholder="Expliquez vos critères d’accompagnement, de consentement et d’encadrement des missions." /></label><Button type="submit" disabled={submit.isPending} className="rounded-full bg-ink py-6 text-paper hover:bg-coral">{submit.isPending ? "Envoi…" : "Envoyer la candidature"}</Button></div></form>; }
function Field({ name, label, type = "text", required = false }: { name: string; label: string; type?: string; required?: boolean }) { return <label><span className="field-label">{label}</span><input required={required} name={name} type={type} className="field-control" /></label>; }
