import { CheckCircle2, ChevronRight, CircleHelp, Euro, Heart } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { AuthGate, PageIntro, SiteFooter, SiteHeader } from "@/components/SiteShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

type RequestForm = { eventType: "mariage" | "prive" | "entreprise" | "culture" | "autre"; eventDate: string; city: string; venue: string; guestCount: string; budget: string; needs: string; contactName: string; contactEmail: string; contactPhone: string; formula: "essentielle" | "collectif" | "sur-mesure"; solidarity: string };
const initialForm: RequestForm = { eventType: "mariage", eventDate: "", city: "", venue: "", guestCount: "", budget: "", needs: "", contactName: "", contactEmail: "", contactPhone: "", formula: "essentielle", solidarity: "0" };
const fees = { essentielle: 18000, collectif: 39000, "sur-mesure": 0 } as const;

export default function RequestPage() {
  return <div className="min-h-screen bg-paper"><SiteHeader /><PageIntro eyebrow="Organisateurs" title="Racontez votre événement. Nous ouvrons le bon chemin.">Décrivez le moment que vous préparez. Vos coordonnées restent dans votre espace de suivi ; seules les personnes autorisées à coordonner la mission y accèdent.</PageIntro><main className="container py-12 md:py-18"><AuthGate title="Enregistrez votre demande en toute confidentialité"><RequestFormContent /></AuthGate></main><SiteFooter /></div>;
}

function RequestFormContent() {
  const [form, setForm] = useState<RequestForm>(initialForm);
  const [submittedId, setSubmittedId] = useState<number | null>(null);
  const createRequest = trpc.requests.create.useMutation({ onSuccess: ({ id }) => { setSubmittedId(id); toast.success("Votre demande est enregistrée."); }, onError: error => toast.error(error.message) });
  const set = <K extends keyof RequestForm>(key: K, value: RequestForm[K]) => setForm(current => ({ ...current, [key]: value }));
  const fee = fees[form.formula];
  const total = fee + (Number(form.solidarity || 0) * 100);
  if (submittedId) return <div className="form-card max-w-2xl"><CheckCircle2 className="h-9 w-9 text-coral" /><p className="eyebrow mt-6">Demande n°{submittedId}</p><h2 className="mt-3 font-editorial text-4xl">Votre demande entre dans le fil de coordination.</h2><p className="mt-4 max-w-xl leading-7 text-ink/65">Vous la retrouverez dans votre espace de suivi. L’équipe prend connaissance de vos besoins avant toute mise en relation.</p><a href="/suivi" className="button-ink mt-7 gap-2">Suivre ma demande <ChevronRight size={17} /></a></div>;
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.budget || Number(form.budget) < 0) return toast.error("Indiquez un budget prévisionnel."); createRequest.mutate({ eventType: form.eventType, eventDate: form.eventDate, city: form.city, venue: form.venue || undefined, guestCount: form.guestCount ? Number(form.guestCount) : undefined, budgetCents: Math.round(Number(form.budget) * 100), needs: form.needs, contactName: form.contactName, contactEmail: form.contactEmail, contactPhone: form.contactPhone || undefined, coordinationFeeCents: fee, solidarityContributionCents: Math.round(Number(form.solidarity || 0) * 100) }); };
  return <form onSubmit={submit} className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_330px]" noValidate>
    <div className="form-card space-y-8"><section><p className="eyebrow">01 · Le moment</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Type d’événement"><select className="field-control" value={form.eventType} onChange={e => set("eventType", e.target.value as RequestForm["eventType"])}><option value="mariage">Mariage</option><option value="prive">Fête privée</option><option value="entreprise">Événement professionnel</option><option value="culture">Rendez-vous culturel</option><option value="autre">Autre projet</option></select></Field><Field label="Date ou période"><input required type="date" className="field-control" value={form.eventDate} onChange={e => set("eventDate", e.target.value)} /></Field><Field label="Ville"><input required className="field-control" placeholder="ex. Lyon" value={form.city} onChange={e => set("city", e.target.value)} /></Field><Field label="Lieu (facultatif)"><input className="field-control" placeholder="Domaine, salle, extérieur…" value={form.venue} onChange={e => set("venue", e.target.value)} /></Field><Field label="Nombre d’invités (facultatif)"><input type="number" min="1" className="field-control" placeholder="ex. 85" value={form.guestCount} onChange={e => set("guestCount", e.target.value)} /></Field></div></section>
    <section className="border-t border-ink/10 pt-8"><p className="eyebrow">02 · Votre besoin</p><Field label="De quoi avez-vous besoin ?" help="Précisez les métiers recherchés, les horaires et l’atmosphère souhaitée."><textarea required className="field-control min-h-36 resize-y" placeholder="Par exemple : accueil de 90 personnes, service au cocktail, une intervention musicale acoustique…" value={form.needs} onChange={e => set("needs", e.target.value)} /></Field></section>
    <section id="budget" className="border-t border-ink/10 pt-8"><p className="eyebrow">03 · Budget et coordination</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Budget prévu pour les prestations"><div className="relative"><Euro className="absolute right-3 top-3.5 h-4 w-4 text-ink/45" /><input required type="number" min="0" className="field-control pr-10" placeholder="ex. 2500" value={form.budget} onChange={e => set("budget", e.target.value)} /></div></Field><Field label="Formule de coordination"><select className="field-control" value={form.formula} onChange={e => set("formula", e.target.value as RequestForm["formula"])}><option value="essentielle">Essentielle · 180 €</option><option value="collectif">Collectif · 390 €</option><option value="sur-mesure">Sur mesure · sur devis</option></select></Field><Field label="Contribution solidaire facultative"><div className="relative"><Heart className="absolute right-3 top-3.5 h-4 w-4 text-coral" /><input type="number" min="0" className="field-control pr-10" placeholder="0" value={form.solidarity} onChange={e => set("solidarity", e.target.value)} /></div></Field></div><p className="mt-4 rounded-xl bg-sand px-4 py-3 text-sm leading-6 text-ink/70">La coordination est affichée avant confirmation. Montant indicatif ajouté à votre dossier : <strong>{form.formula === "sur-mesure" ? "sur devis" : `${(total / 100).toLocaleString("fr-FR", { style: "currency", currency: "EUR" })}`}</strong>. Aucun paiement n’est demandé à cette étape.</p></section>
    <section className="border-t border-ink/10 pt-8"><p className="eyebrow">04 · Vos coordonnées</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Votre nom"><input required className="field-control" value={form.contactName} onChange={e => set("contactName", e.target.value)} /></Field><Field label="Votre e-mail"><input required type="email" className="field-control" value={form.contactEmail} onChange={e => set("contactEmail", e.target.value)} /></Field><Field label="Téléphone (facultatif)"><input className="field-control" value={form.contactPhone} onChange={e => set("contactPhone", e.target.value)} /></Field></div></section>
    <Button type="submit" disabled={createRequest.isPending} className="w-full rounded-full bg-ink py-6 text-paper hover:bg-coral">{createRequest.isPending ? "Enregistrement…" : "Envoyer ma demande"}</Button>
    </div>
    <aside className="h-fit rounded-[1.5rem] bg-ink p-6 text-paper lg:sticky lg:top-24"><CircleHelp className="text-lime" /><h2 className="mt-8 font-editorial text-3xl">Ce qui se passe ensuite</h2><ol className="mt-6 space-y-5 text-sm leading-6 text-paper/70"><li><span className="mr-2 font-mono text-lime">01</span>Votre demande est lue par la coordination.</li><li><span className="mr-2 font-mono text-lime">02</span>Les besoins sont précisés, si nécessaire.</li><li><span className="mr-2 font-mono text-lime">03</span>Une présélection est proposée avec des conditions claires.</li><li><span className="mr-2 font-mono text-lime">04</span>La mission est confirmée seulement avec l’accord des personnes concernées.</li></ol></aside>
  </form>;
}

function Field({ label, help, children }: { label: string; help?: string; children: React.ReactNode }) { return <label className="block"><span className="field-label">{label}</span>{children}{help && <span className="field-help">{help}</span>}</label>; }
