import { CheckCircle2, Eye, LockKeyhole, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { AuthGate, PageIntro, SiteFooter, SiteHeader } from "@/components/SiteShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

type TalentForm = { professionalName: string; headline: string; city: string; region: string; category: "accueil" | "service" | "animation" | "technique" | "art" | "logistique"; skills: string; bio: string; accessPath: "independant" | "accompagne"; availableFrom: string; availableTo: string; availabilityNote: string; consent: boolean; isOpen: boolean };
const initial: TalentForm = { professionalName: "", headline: "", city: "", region: "", category: "accueil", skills: "", bio: "", accessPath: "independant", availableFrom: "", availableTo: "", availabilityNote: "", consent: false, isOpen: true };

export default function TalentPage() { return <div className="min-h-screen bg-paper"><SiteHeader /><PageIntro eyebrow="Talents" title="Votre savoir-faire mérite d’être vu, jamais réduit.">Présentez vos compétences, choisissez votre disponibilité et gardez la main sur la visibilité de votre profil. L’accompagnement par une structure partenaire est une possibilité, jamais une étiquette publique.</PageIntro><main className="container py-12 md:py-18"><AuthGate title="Créez votre profil de compétences"><TalentFormContent /></AuthGate></main><SiteFooter /></div>; }

function TalentFormContent() {
  const [form, setForm] = useState<TalentForm>(initial); const [done, setDone] = useState(false); const save = trpc.talents.save.useMutation({ onSuccess: () => { setDone(true); toast.success("Votre profil a été transmis à la coordination."); }, onError: error => toast.error(error.message) });
  const set = <K extends keyof TalentForm>(key: K, value: TalentForm[K]) => setForm(current => ({ ...current, [key]: value }));
  if (done) return <div className="form-card max-w-2xl"><CheckCircle2 className="h-9 w-9 text-coral" /><p className="eyebrow mt-6">Profil reçu</p><h2 className="mt-3 font-editorial text-4xl">Votre profil attend une validation humaine.</h2><p className="mt-4 leading-7 text-ink/65">Il n’est pas visible dans l’annuaire tant que la coordination n’a pas validé les informations et, si vous l’avez indiqué, le cadre de la structure partenaire.</p></div>;
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.consent) return toast.error("Votre consentement explicite est nécessaire pour déposer le profil."); save.mutate({ professionalName: form.professionalName, headline: form.headline, city: form.city, region: form.region, category: form.category, skills: form.skills, bio: form.bio, accessPath: form.accessPath, consentPublic: true, isOpenToMissions: form.isOpen, availableFrom: form.availableFrom || undefined, availableTo: form.availableTo || undefined, availabilityNote: form.availabilityNote || undefined }); };
  return <form onSubmit={submit} className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_330px]" noValidate><div className="form-card space-y-8"><section><p className="eyebrow">01 · Votre carte professionnelle</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Nom professionnel"><input required className="field-control" placeholder="Prénom ou nom d’activité" value={form.professionalName} onChange={e => set("professionalName", e.target.value)} /></Field><Field label="Titre / savoir-faire"><input required className="field-control" placeholder="ex. Régisseuse accueil & hospitalité" value={form.headline} onChange={e => set("headline", e.target.value)} /></Field><Field label="Ville"><input required className="field-control" value={form.city} onChange={e => set("city", e.target.value)} /></Field><Field label="Région"><input required className="field-control" placeholder="ex. Auvergne-Rhône-Alpes" value={form.region} onChange={e => set("region", e.target.value)} /></Field><Field label="Domaine"><select className="field-control" value={form.category} onChange={e => set("category", e.target.value as TalentForm["category"])}><option value="accueil">Accueil</option><option value="service">Service</option><option value="animation">Animation</option><option value="technique">Technique</option><option value="art">Art</option><option value="logistique">Logistique</option></select></Field></div><Field label="Compétences et outils" help="Séparez les compétences par une virgule pour rendre la recherche plus précise."><input required className="field-control" placeholder="ex. accueil invités, billetterie, anglais, coordination" value={form.skills} onChange={e => set("skills", e.target.value)} /></Field><Field label="Votre présentation" help="Présentez votre manière de travailler et ce que vous aimez apporter à une mission. N’indiquez aucune donnée sensible."><textarea required className="field-control min-h-36 resize-y" value={form.bio} onChange={e => set("bio", e.target.value)} /></Field></section>
  <section className="border-t border-ink/10 pt-8"><p className="eyebrow">02 · Votre disponibilité</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Disponible à partir du"><input type="date" className="field-control" value={form.availableFrom} onChange={e => set("availableFrom", e.target.value)} /></Field><Field label="Jusqu’au"><input type="date" className="field-control" value={form.availableTo} onChange={e => set("availableTo", e.target.value)} /></Field></div><Field label="Précisions (facultatif)"><input className="field-control" placeholder="ex. Jeudi à dimanche, mobilité régionale" value={form.availabilityNote} onChange={e => set("availabilityNote", e.target.value)} /></Field></section>
  <section className="border-t border-ink/10 pt-8"><p className="eyebrow">03 · Accompagnement et consentement</p><div className="mt-5 space-y-3"><label className="flex cursor-pointer gap-3 rounded-xl border border-ink/10 p-4"><input type="radio" checked={form.accessPath === "independant"} onChange={() => set("accessPath", "independant")} /><span><strong className="text-sm">Je dépose mon profil de façon autonome.</strong><span className="mt-1 block text-xs leading-5 text-ink/60">Aucune information d’accompagnement n’est visible dans l’annuaire.</span></span></label><label className="flex cursor-pointer gap-3 rounded-xl border border-ink/10 p-4"><input type="radio" checked={form.accessPath === "accompagne"} onChange={() => set("accessPath", "accompagne")} /><span><strong className="text-sm">Je suis accompagné·e par une structure partenaire.</strong><span className="mt-1 block text-xs leading-5 text-ink/60">La structure est vérifiée par la coordination. Votre parcours n’est jamais affiché publiquement.</span></span></label></div><label className="mt-5 flex cursor-pointer gap-3 rounded-xl bg-sand p-4"><input required type="checkbox" checked={form.consent} onChange={e => set("consent", e.target.checked)} /><span className="text-sm leading-5"><strong>Je consens explicitement à la publication de ce profil de compétences</strong>, après validation de la coordination. Je peux demander son retrait ou modifier mon accord à tout moment.</span></label><label className="mt-3 flex cursor-pointer gap-3 text-sm"><input type="checkbox" checked={form.isOpen} onChange={e => set("isOpen", e.target.checked)} />Je suis actuellement ouvert·e à de nouvelles missions.</label></section><Button type="submit" disabled={save.isPending} className="w-full rounded-full bg-ink py-6 text-paper hover:bg-coral">{save.isPending ? "Transmission…" : "Transmettre mon profil"}</Button></div>
  <aside className="h-fit space-y-4 lg:sticky lg:top-24"><div className="rounded-[1.5rem] bg-ink p-6 text-paper"><Eye className="text-lime" /><h2 className="mt-7 font-editorial text-3xl">Ce qui sera visible</h2><p className="mt-4 text-sm leading-6 text-paper/70">Votre nom professionnel, savoir-faire, zone géographique, compétences et disponibilité. Rien de plus.</p></div><div className="rounded-[1.5rem] bg-lime p-6"><LockKeyhole className="text-coral" /><h2 className="mt-7 font-editorial text-3xl">Ce qui reste privé</h2><p className="mt-4 text-sm leading-6 text-ink/68">Vos coordonnées, votre situation personnelle et les détails de tout accompagnement. Ils ne sont partagés qu’avec votre accord.</p></div><div className="rounded-[1.5rem] border border-ink/10 p-6"><ShieldCheck className="text-coral" /><p className="mt-4 text-sm leading-6 text-ink/65">Un problème ? Un dispositif de signalement confidentiel est disponible à tout moment.</p></div></aside></form>;
}
function Field({ label, help, children }: { label: string; help?: string; children: React.ReactNode }) { return <label className="mb-5 block"><span className="field-label">{label}</span>{children}{help && <span className="field-help">{help}</span>}</label>; }
